/** Provincias y ciudades de Argentina para el selector de ubicación. */
export const ARGENTINA_PROVINCES = [
  {
    code: "BA",
    name: "Buenos Aires",
    cities: [
      "Buenos Aires",
      "La Plata",
      "Quilmes",
      "Avellaneda",
      "Lomas de Zamora",
      "Morón",
      "Merlo",
      "Florencio Varela",
      "San Martín",
      "Lanús",
      "Bernal",
      "Temperley",
      "Berazategui",
      "Adrogué",
      "Almirante Brown",
      "Banfield",
      "Castelar",
      "Ciudad Evita",
      "Ciudadela",
      "Donato Álvarez",
      "Hurlingham",
      "Ituzaingó",
      "José C. Paz",
      "La Matanza",
      "Las Flores",
      "Malvinas Argentinas",
      "Martínez",
      "Mataderos",
      "Moron",
      "Navarro",
      "Olivos",
      "Pacheco",
      "Parque Chacabuco",
      "Pergamino",
      "Pilar",
      "Presidente Perón",
      "Puente Vela",
      "Ranelagh",
      "Ramos Mejía",
      "San Andrés de Giles",
      "San Fernandinos",
      "San Fernando",
      "San Isidro",
      "San Justo",
      "San Nicolás",
      "San Vicente",
      "Sarandí",
      "Suburbano",
      "Tapiales",
      "Tigre",
      "Tolosa",
      "Tortuguitas",
      "Flores",
      "Flores del Día",
      "Floresta",
      "Fuerte Apache",
      "Gregorio de Laferrere",
      "Guernica",
      "Guillermo Juan Davis",
      "Haedo",
      "Haedo Oeste",
    ],
  },
  {
    code: "CA",
    name: "Catamarca",
    cities: [
      "San Fernando del Valle de Catamarca",
      "Andalgalá",
      "Belén",
      "Fiambalá",
      "Tinogasta",
      "Santa Rosa de Tastil",
    ],
  },
  {
    code: "CB",
    name: "Chubut",
    cities: ["Rawson", "Comodoro Rivadavia", "Puerto Madryn", "Esquel", "Trelew", "El Maitén", "Gobernador Costa"],
  },
  {
    code: "CO",
    name: "Córdoba",
    cities: [
      "Córdoba",
      "Jesús María",
      "Río Cuarto",
      "Villa María",
      "Morteros",
      "Cosquín",
      "La Falda",
      "Villa Carlos Paz",
      "San Francisco",
      "Pilar",
      "Capilla del Monte",
      "Colón",
      "Cruz del Eje",
      "Deán Funes",
      "Dique",
      "Dolores",
      "Huerta Grande",
      "Juárez Celman",
      "Laboulaye",
      "La Carlota",
      "La Cumbrecita",
      "Las Higueras",
      "Leones",
      "Luján",
      "Mina Clavero",
      "Monsalvo",
      "Montecristo",
      "Nicolás Avellaneda",
      "Obispo Trejo",
      "Oncativo",
      "Pando",
      "Parque Sarmiento",
      "Paso de Flores",
      "Piedra Blanca",
      "Piedras Blancas",
      "Piedras Negras",
      "Villa Allende",
      "Villa Dolores",
      "Villa General Belgrano",
      "Villa Rumipal",
    ],
  },
  {
    code: "ER",
    name: "Entre Ríos",
    cities: [
      "Paraná",
      "Concordia",
      "Gualeguaychú",
      "Victoria",
      "Federal",
      "Federación",
      "Diamante",
      "Rosario del Tala",
      "Villaguay",
      "Viedma",
      "Colón",
    ],
  },
  {
    code: "FO",
    name: "Formosa",
    cities: ["Formosa", "Clorinda", "Pirané", "Ibarreta", "Ingeniero Juárez"],
  },
  {
    code: "JU",
    name: "Jujuy",
    cities: [
      "San Salvador de Jujuy",
      "Palpalá",
      "Libertador General San Martín",
      "Perico",
      "Maimará",
      "Monterrico",
      "Purmamarca",
      "Tilcara",
      "Volcán",
    ],
  },
  {
    code: "LA",
    name: "La Pampa",
    cities: ["Santa Rosa", "General Pico", "Realicó", "Macachín", "Quemú Quemú", "Eduardo Castex"],
  },
  {
    code: "LR",
    name: "La Rioja",
    cities: ["La Rioja", "Chilecito", "Famatina", "Aimogasta", "Chepes"],
  },
  {
    code: "ME",
    name: "Mendoza",
    cities: [
      "Mendoza",
      "Godoy Cruz",
      "Las Heras",
      "Maipú",
      "Luján de Cuyo",
      "Guaymallén",
      "San Martín",
      "Junín",
      "Rivadavia",
      "San Rafael",
      "General Alvear",
      "Tunuyán",
    ],
  },
  {
    code: "MI",
    name: "Misiones",
    cities: ["Posadas", "Oberá", "Puerto Iguazú", "Eldorado", "Garupá", "Iguazú", "Aristóbulo del Valle"],
  },
  {
    code: "NE",
    name: "Neuquén",
    cities: [
      "Neuquén",
      "Zapala",
      "San Martín de los Andes",
      "Junín de los Andes",
      "Chos Malal",
      "Pehuajó",
      "Villa La Angostura",
    ],
  },
  {
    code: "RN",
    name: "Río Negro",
    cities: [
      "Viedma",
      "Cipolletti",
      "Bariloche",
      "Roca",
      "Ingeniero Jacobacci",
      "Pico Truncado",
      "El Bolsón",
      "Villa Regina",
    ],
  },
  {
    code: "SA",
    name: "Salta",
    cities: [
      "Salta",
      "San Ramón de la Nueva Orán",
      "Tartagal",
      "Rosario de Lerma",
      "La Caldera",
      "Campo Quijano",
      "Cerrillos",
      "Chicoana",
      "Guachipas",
      "Cafayate",
      "Metán",
      "Embarcación",
    ],
  },
  {
    code: "SJ",
    name: "San Juan",
    cities: [
      "San Juan",
      "Chimbas",
      "Rivadavia",
      "Calingasta",
      "Jáchal",
      "Iglesia",
      "Angaco",
      "Caucete",
      "Pocito",
      "Santa Lucía",
      "Sarmiento",
      "Ullum",
      "Valle Fértil",
      "Zonda",
    ],
  },
  {
    code: "SL",
    name: "San Luis",
    cities: [
      "San Luis",
      "Villa Mercedes",
      "Merlo",
      "Ayacucho",
      "Luján",
      "Carolina",
      "Concarán",
      "El Chorrillo",
      "Gobernador Dupuy",
      "Gobernador Gómez",
      "La Cañada",
      "La Toma",
      "Lafinur",
      "Las Chacras",
      "Las Lajitas",
      "Lauquen",
      "Leucoma",
      "Naschel",
      "Quines",
      "San Francisco del Monte de Oro",
      "Tilisarao",
      "Unión",
      "Villa de la Quebrada",
      "Villa de Praga",
      "Villa General Roca",
      "Villa Larca",
      "Villa Reynolds",
    ],
  },
  {
    code: "SF",
    name: "Santa Fe",
    cities: [
      "Rosario",
      "Santa Fe",
      "Funes",
      "Capitán Bermúdez",
      "Granadero Baigorria",
      "Arroyo Seco",
      "Rufino",
      "Venado Tuerto",
      "San Cristóbal",
      "Coronda",
      "Santo Tomé",
      "Cañada de Gómez",
      "Casilda",
      "Acebal",
      "Alcántara",
      "Álvarez",
      "Arandú",
      "Arrecifes",
      "Arroyito",
      "Ataliva",
      "Aurelia",
      "Avellaneda",
      "Recreo",
      "Rafaela",
      "Esperanza",
      "Gálvez",
      "Villa Gobernador Gálvez",
      "Pérez",
      "Firmat",
    ],
  },
  {
    code: "SE",
    name: "Santiago del Estero",
    cities: [
      "Santiago del Estero",
      "La Banda",
      "Termas de Río Hondo",
      "Frías",
      "Loreto",
      "Selva",
      "Quimilí",
      "Fernández",
    ],
  },
  {
    code: "TF",
    name: "Tierra del Fuego",
    cities: ["Ushuaia", "Río Grande", "Tolhuin"],
  },
  {
    code: "TM",
    name: "Tucumán",
    cities: [
      "San Miguel de Tucumán",
      "Yerba Buena",
      "Tafí Viejo",
      "Concepción",
      "Monteros",
      "Lules",
      "Aguilares",
      "Alderetes",
      "Bella Vista",
      "Famaillá",
      "Tafí del Valle",
      "Chicligasta",
    ],
  },
  {
    code: "CH",
    name: "Chaco",
    cities: ["Resistencia", "Presidencia Roque Sáenz Peña", "Barranqueras", "Fontana", "Charata", "Villa Ángela"],
  },
  {
    code: "CR",
    name: "Corrientes",
    cities: ["Corrientes", "Goya", "Paso de los Libres", "Curuzú Cuatiá", "Mercedes", "Bella Vista", "Esquina"],
  },
  {
    code: "SC",
    name: "Santa Cruz",
    cities: ["Río Gallegos", "Caleta Olivia", "El Calafate", "Pico Truncado", "Puerto Deseado", "Las Heras"],
  },
] as const;
