/** Provincias y ciudades de Argentina para el selector de ubicación. */
export const ARGENTINA_PROVINCES = [
  {
    code: "CABA",
    name: "Ciudad Autónoma de Buenos Aires",
    cities: [
      "Buenos Aires",
      "Palermo",
      "Belgrano",
      "Caballito",
      "Almagro",
      "Villa Crespo",
      "Flores",
      "Boedo",
      "Liniers",
      "Villa del Parque",
      "Villa Devoto",
      "Saavedra",
      "Núñez",
      "Villa Urquiza",
      "Recoleta",
      "San Telmo",
      "Barracas",
      "Parque Patricios",
      "Villa Lugano",
      "Floresta",
      "Balvanera",
      "La Boca",
      "Chacarita",
      "Villa Pueyrredón",
      "Paternal",
      "Monte Castro",
      "Mataderos",
      "Villa Luro",
      "Colegiales",
      "Versalles",
    ],
  },
  {
    code: "BA",
    name: "Buenos Aires",
    cities: [
      "La Plata",
      "Mar del Plata",
      "Bahía Blanca",
      "Quilmes",
      "Avellaneda",
      "Lomas de Zamora",
      "Morón",
      "Merlo",
      "Florencio Varela",
      "San Martín",
      "Lanús",
      "Bernal",
      "Temperley",
      "Berazategui",
      "Adrogué",
      "Almirante Brown",
      "Banfield",
      "Castelar",
      "Hurlingham",
      "Ituzaingó",
      "José C. Paz",
      "La Matanza",
      "Malvinas Argentinas",
      "Martínez",
      "Moreno",
      "Olivos",
      "Pergamino",
      "Pilar",
      "Presidente Perón",
      "Ramos Mejía",
      "Ranelagh",
      "San Andrés de Giles",
      "San Fernando",
      "San Isidro",
      "San Justo",
      "San Miguel",
      "San Nicolás de los Arroyos",
      "San Pedro",
      "San Vicente",
      "Sarandí",
      "Tigre",
      "Tolosa",
      "Tortuguitas",
      "Haedo",
      "Tapiales",
      "Gregorio de Laferrere",
      "Guernica",
      "Navarro",
      "Tandil",
      "Olavarría",
      "Junín",
      "Necochea",
      "Azul",
      "Luján",
      "Campana",
      "Zárate",
      "Chascomús",
      "Tres Arroyos",
      "Punta Alta",
      "Balcarce",
      "Coronel Suárez",
      "Miramar",
      "Villa Gesell",
      "Pinamar",
      "Escobar",
      "Belén de Escobar",
      "Garín",
      "Ezeiza",
      "Monte Grande",
      "Lobos",
      "Bragado",
      "Chacabuco",
      "Lincoln",
      "Trenque Lauquen",
      "Pehuajó",
      "Rojas",
      "Ramallo",
      "Baradero",
      "Marcos Paz",
      "General Rodríguez",
      "Cañuelas",
      "Dolores",
      "Las Flores",
      "Lobería",
      "Benito Juárez",
      "Rauch",
      "Ayacucho",
      "Brandsen",
      "General Belgrano",
      "25 de Mayo",
      "Nueve de Julio",
      "Carmen de Areco",
      "Monte Hermoso",
      "San Clemente del Tuyú",
      "Santa Teresita",
      "Mar de Ajó",
      "General Madariaga",
      "Coronel Pringles",
      "Coronel Dorrego",
      "Salto",
      "Arrecifes",
      "Del Viso",
      "General Pacheco",
      "Ingeniero Maschwitz",
      "Don Torcuato",
      "Capilla del Señor",
      "Presidente Derqui",
      "Villa Rosa",
      "Nordelta",
      "San Bernardo",
      "Las Toninas",
      "Villa Gessel",
    ],
  },
  {
    code: "CA",
    name: "Catamarca",
    cities: [
      "San Fernando del Valle de Catamarca",
      "Andalgalá",
      "Belén",
      "Fiambalá",
      "Tinogasta",
      "Santa María",
      "Recreo",
      "Concepción",
      "Pomán",
      "Hualfín",
    ],
  },
  {
    code: "CH",
    name: "Chaco",
    cities: [
      "Resistencia",
      "Presidencia Roque Sáenz Peña",
      "Barranqueras",
      "Fontana",
      "Charata",
      "Villa Ángela",
      "Machagai",
      "Quitilipi",
      "Presidencia Roca",
      "General San Martín",
      "Las Breñas",
      "Juan José Castelli",
      "Campo Largo",
      "Corzuela",
    ],
  },
  {
    code: "CU",
    name: "Chubut",
    cities: [
      "Rawson",
      "Comodoro Rivadavia",
      "Puerto Madryn",
      "Trelew",
      "Esquel",
      "Rada Tilly",
      "Gaiman",
      "Dolavon",
      "Sarmiento",
      "Río Mayo",
      "Camarones",
      "Cholila",
      "El Maitén",
      "Gobernador Costa",
      "Lago Puelo",
      "Puerto Pirámides",
    ],
  },
  {
    code: "CO",
    name: "Córdoba",
    cities: [
      "Córdoba",
      "Alta Gracia",
      "Río Cuarto",
      "Villa María",
      "Bell Ville",
      "Río Tercero",
      "Villa Nueva",
      "San Francisco",
      "Jesús María",
      "Cosquín",
      "La Falda",
      "Villa Carlos Paz",
      "Pilar",
      "Capilla del Monte",
      "Cruz del Eje",
      "Deán Funes",
      "Huerta Grande",
      "Laboulaye",
      "La Carlota",
      "La Cumbrecita",
      "Leones",
      "Mina Clavero",
      "Montecristo",
      "Morteros",
      "Oncativo",
      "Villa Allende",
      "Villa Dolores",
      "Villa General Belgrano",
      "Villa Rumipal",
      "Marcos Juárez",
      "Arroyito",
      "General Deheza",
      "General Cabrera",
      "Las Varillas",
      "Brinkmann",
      "Colonia Caroya",
      "Malagueño",
      "Unquillo",
      "Mendiolaza",
      "Río Segundo",
      "Monte Maíz",
      "Almafuerte",
      "Hernando",
      "James Craik",
      "Oliva",
      "Vicuña Mackenna",
      "Río Ceballos",
      "Villa del Totoral",
      "Salsipuedes",
      "La Calera",
      "Colón",
      "Tancacha",
      "Sampacho",
      "Bialet Massé",
      "San Antonio de Arredondo",
      "Villa del Dique",
      "Embalse",
      "General Roca",
    ],
  },
  {
    code: "CR",
    name: "Corrientes",
    cities: [
      "Corrientes",
      "Goya",
      "Paso de los Libres",
      "Curuzú Cuatiá",
      "Mercedes",
      "Bella Vista",
      "Esquina",
      "Santo Tomé",
      "Ituzaingó",
      "Monte Caseros",
      "Saladas",
      "Mburucuyá",
      "Sauce",
      "Empedrado",
    ],
  },
  {
    code: "ER",
    name: "Entre Ríos",
    cities: [
      "Paraná",
      "Concordia",
      "Gualeguaychú",
      "Victoria",
      "Federal",
      "Federación",
      "Diamante",
      "Rosario del Tala",
      "Villaguay",
      "Colón",
      "Concepción del Uruguay",
      "Chajarí",
      "San José",
      "La Paz",
      "Basavilbaso",
      "Hasenkamp",
      "Crespo",
      "Nogoyá",
      "Gualeguay",
      "Viale",
      "Urdinarrain",
      "Gilbert",
    ],
  },
  {
    code: "FO",
    name: "Formosa",
    cities: [
      "Formosa",
      "Clorinda",
      "Pirané",
      "Ibarreta",
      "Ingeniero Juárez",
      "El Colorado",
      "Las Lomitas",
      "Pozo del Tigre",
    ],
  },
  {
    code: "JU",
    name: "Jujuy",
    cities: [
      "San Salvador de Jujuy",
      "Palpalá",
      "Libertador General San Martín",
      "Perico",
      "San Pedro de Jujuy",
      "Maimará",
      "Monterrico",
      "Purmamarca",
      "Tilcara",
      "Volcán",
      "Humahuaca",
      "La Quiaca",
      "Abra Pampa",
      "Fraile Pintado",
      "Calilegua",
      "Yuto",
    ],
  },
  {
    code: "LP",
    name: "La Pampa",
    cities: [
      "Santa Rosa",
      "General Pico",
      "Realicó",
      "Macachín",
      "Quemú Quemú",
      "Eduardo Castex",
      "Toay",
      "Victorica",
      "General Acha",
      "Winifreda",
      "Intendente Alvear",
      "Rancul",
      "Catriló",
    ],
  },
  {
    code: "LR",
    name: "La Rioja",
    cities: [
      "La Rioja",
      "Chilecito",
      "Famatina",
      "Aimogasta",
      "Chepes",
      "Villa Unión",
      "Chamical",
      "Vinchina",
      "Nonogasta",
    ],
  },
  {
    code: "ME",
    name: "Mendoza",
    cities: [
      "Mendoza",
      "Godoy Cruz",
      "Las Heras",
      "Maipú",
      "Luján de Cuyo",
      "Guaymallén",
      "San Martín",
      "Junín",
      "Rivadavia",
      "San Rafael",
      "General Alvear",
      "Tunuyán",
      "Lavalle",
      "Santa Rosa",
      "San Carlos",
      "Malargüe",
      "Tupungato",
      "Palmira",
      "Rodeo del Medio",
      "La Paz",
    ],
  },
  {
    code: "MI",
    name: "Misiones",
    cities: [
      "Posadas",
      "Oberá",
      "Puerto Iguazú",
      "Eldorado",
      "Garupá",
      "Aristóbulo del Valle",
      "San Vicente",
      "Montecarlo",
      "Apóstoles",
      "Leandro N. Alem",
      "Campo Viera",
      "Jardín América",
      "San Ignacio",
      "Puerto Rico",
      "San Pedro",
    ],
  },
  {
    code: "NE",
    name: "Neuquén",
    cities: [
      "Neuquén",
      "Plottier",
      "Centenario",
      "Zapala",
      "San Martín de los Andes",
      "Junín de los Andes",
      "Chos Malal",
      "Villa La Angostura",
      "Cutral-Có",
      "Plaza Huincul",
      "Rincón de los Sauces",
      "Loncopué",
      "Las Lajas",
      "Senillosa",
      "Aluminé",
      "Piedra del Águila",
    ],
  },
  {
    code: "RN",
    name: "Río Negro",
    cities: [
      "Viedma",
      "Cipolletti",
      "Bariloche",
      "General Roca",
      "Allen",
      "Cinco Saltos",
      "El Bolsón",
      "Villa Regina",
      "Catriel",
      "Ingeniero Jacobacci",
      "Río Colorado",
      "Lamarque",
      "Luis Beltrán",
      "Choele Choel",
      "Las Grutas",
      "Sierra Grande",
    ],
  },
  {
    code: "SA",
    name: "Salta",
    cities: [
      "Salta",
      "San Ramón de la Nueva Orán",
      "Tartagal",
      "General Güemes",
      "Rosario de Lerma",
      "Cerrillos",
      "Chicoana",
      "Cafayate",
      "Metán",
      "Embarcación",
      "Joaquín V. González",
      "Campo Quijano",
      "La Caldera",
      "El Galpón",
      "Salvador Mazza",
      "Aguaray",
      "Pichanal",
    ],
  },
  {
    code: "SJ",
    name: "San Juan",
    cities: [
      "San Juan",
      "Chimbas",
      "Rawson",
      "Rivadavia",
      "Caucete",
      "Pocito",
      "Santa Lucía",
      "Angaco",
      "Calingasta",
      "Jáchal",
      "Iglesia",
      "Sarmiento",
      "Ullum",
      "Valle Fértil",
      "Zonda",
      "Albardón",
    ],
  },
  {
    code: "SL",
    name: "San Luis",
    cities: [
      "San Luis",
      "Villa Mercedes",
      "Merlo",
      "San Francisco del Monte de Oro",
      "La Toma",
      "Concarán",
      "Naschel",
      "Quines",
      "Tilisarao",
      "Villa Reynolds",
      "Justo Daract",
      "Nueva Galia",
      "Balde",
    ],
  },
  {
    code: "SC",
    name: "Santa Cruz",
    cities: [
      "Río Gallegos",
      "Caleta Olivia",
      "El Calafate",
      "Pico Truncado",
      "Puerto Deseado",
      "Las Heras",
      "Puerto Santa Cruz",
      "El Chaltén",
      "Los Antiguos",
      "Perito Moreno",
      "Gobernador Gregores",
      "San Julián",
    ],
  },
  {
    code: "SF",
    name: "Santa Fe",
    cities: [
      "Rosario",
      "Santa Fe",
      "Rafaela",
      "Venado Tuerto",
      "Santo Tomé",
      "Reconquista",
      "Casilda",
      "Esperanza",
      "Villa Constitución",
      "San Lorenzo",
      "Granadero Baigorria",
      "Capitán Bermúdez",
      "Funes",
      "Roldán",
      "Pérez",
      "Villa Gobernador Gálvez",
      "Arroyo Seco",
      "Cañada de Gómez",
      "Gálvez",
      "Coronda",
      "Firmat",
      "Rufino",
      "San Cristóbal",
      "Armstrong",
      "Las Parejas",
      "Las Rosas",
      "Totoras",
      "Sunchales",
      "Carcarañá",
      "Ceres",
      "San Justo",
      "Vera",
      "Tostado",
      "Laguna Paiva",
      "Frontera",
      "San Carlos Centro",
      "Malabrigo",
      "Pueblo Esther",
      "Ibarlucea",
      "Oliveros",
      "Puerto General San Martín",
      "Soldini",
      "Zavalla",
      "San Genaro",
      "Sastre",
      "Wheelwright",
      "Villa Cañás",
      "Elortondo",
      "Avellaneda",
      "Acebal",
      "Álvarez",
      "Recreo",
      "Serodino",
      "Tortugas",
      "Correa",
    ],
  },
  {
    code: "SE",
    name: "Santiago del Estero",
    cities: [
      "Santiago del Estero",
      "La Banda",
      "Termas de Río Hondo",
      "Frías",
      "Loreto",
      "Quimilí",
      "Fernández",
      "Añatuya",
      "Beltrán",
      "Monte Quemado",
      "Clodomira",
      "Nueva Esperanza",
    ],
  },
  {
    code: "TF",
    name: "Tierra del Fuego",
    cities: [
      "Ushuaia",
      "Río Grande",
      "Tolhuin",
    ],
  },
  {
    code: "TU",
    name: "Tucumán",
    cities: [
      "San Miguel de Tucumán",
      "Yerba Buena",
      "Tafí Viejo",
      "Banda del Río Salí",
      "Alderetes",
      "El Manantial",
      "Concepción",
      "Monteros",
      "Lules",
      "Aguilares",
      "Bella Vista",
      "Famaillá",
      "Tafí del Valle",
      "Cruz Alta",
      "Simoca",
      "Trancas",
      "La Cocha",
      "Ranchillos",
    ],
  },
] as const;
